### ISSUE TITLE
could not find class AutoValue_Crumb and AutoValue_SystemInfo

### ISSUE THREAD

**Issue by hudan15** [cdancy/jenkins-rest#105]
private static Crumb create(final String value, final String sessionIdCookie,
            final List<Error> errors) {

        return new AutoValue_Crumb(JenkinsUtils.nullToEmpty(errors), value,
                sessionIdCookie);
    }

    @SerializedNames({ "hudsonVersion", "jenkinsVersion", "jenkinsSession",
        "instanceIdentity", "sshEndpoint", "server", "errors" })
    public static SystemInfo create(String hudsonVersion, String jenkinsVersion, String jenkinsSession,
            String instanceIdentity,
            String sshEndpoint, String server, final List<Error> errors) {
        return new AutoValue_SystemInfo(JenkinsUtils.nullToEmpty(errors),
                hudsonVersion, jenkinsVersion, jenkinsSession, 
                instanceIdentity, sshEndpoint, server);
    }

**Comment by hudan15** [comment]
when I bulid this project,all class start with "AutoValue" couldn't find

**Comment by cdancy** [comment]
@hudan15 how are you building the project? When I run `./gradlew build` all works fine for me. Are you building through an IDE or some other non-standard way?

**Comment by cdancy** [comment]
@hudan15 also just updated gradle and some of the project dependent libraries, and how things are defined, so that _may_ help you along. I'd pull the latest and greatest code and give things another go.

**Comment by hudan15** [comment]
I  built this project through Intellij IDEA .I reimport this project and use mirror to download dependencies ,it works.Thanks for your answer.
