### ISSUE TITLE
Remote connection closed error when making any calls

### ISSUE THREAD

**Issue by ismailmayat** [cdancy/jenkins-rest#110]
### Expected Behavior
Tried to make calls to build and Get however get following error:

> Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.

I tried to setup TLS and also tried to ignore any SSL errors but still get same error.

`ServicePointManager.SecurityProtocol = SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls12;
            ServicePointManager.ServerCertificateValidationCallback +=  (sender, certificate, chain, sslPolicyErrors) => true;`

When I make curl requests using same build url and user and token it works fine.

### Your Environment
I am running windows server 2016 and Jenkins ver. 2.222.1
My client code is .net 45

**Comment by cdancy** [comment]
hmmm ... @ismailmayat this is for the `jenkins-rest` java client library. Are you sure this is the right place to be asking that question? Maybe just looking for help?

**Comment by ismailmayat** [comment]
oops sorry wrong project my bad
