### ISSUE TITLE
jclouds.proxy-host not working

### ISSUE THREAD

**Issue by sorend** [cdancy/jenkins-rest#119]
### Expected Behavior

I was expecting that I could use proxy settings of jclouds, but there seems to be some problem with dependencies. Looks to me like the use of guice pulls versions of guice and guava that are incompatible with jclouds, and especially in the case of accessing Jenkins over http proxy.

### Current Behavior

```
        Properties props = new Properties()
        props.setProperty('jclouds.proxy-host', '10.10.10.10')
        props.setProperty('jclouds.proxy-port', '8080')

        JenkinsClient client = JenkinsClient.builder()
                .endPoint("https://some.com")
                .credentials("none:secret")
                .overrides(props)
                .build()

        SystemInfo info = client.api().systemApi().systemInfo()

```

Returns:
`SystemInfo{errors=[Error{context=null, message=Unexpected exception being thrown: error=Error{context=null, message='java.lang.String com.google.common.net.HostAndPort.getHostText()', exceptionName=java.lang.NoSuchMethodError} connecting to HEAD https://some.com/ HTTP/1.1, exceptionName=org.jclouds.http.HttpResponseException}], hudsonVersion=-1, jenkinsVersion=-1, jenkinsSession=-1, instanceIdentity=-1, sshEndpoint=-1, server=-1}`

**Comment by cdancy** [comment]
@sorend intersting ... have you seen this pop elsewhere or **only** when using the proxy property?

**Comment by sorend** [comment]
I have not used the library extensively yet, but haven't run into other problems as of now (when using the library with a Jenkins that is not behind proxy)

It appears it might've been fixed in Jclouds:
https://github.com/apache/jclouds/commit/62767a14610fc1c97c440dbd5ee0f02b276a1069#diff-01bcf54846bea2a9e8cd661cde19f0fd

But, as far as I can see there is no release after the fix.

BR,
Søren

**Comment by cdancy** [comment]
@sorend commented on the [relevant PR](https://github.com/apache/jclouds/pull/75). Hopefully they can kick a release and once they do it will be very simple to do the same here. Lets see what they say. Those guys are usually pretty good.

**Comment by ChorusIdea** [comment]
You can try to use jvm proxy as alternative
Properties props = new Properties();
props.setProperty("jclouds.enable-jvm-proxy", "true");

then pass the arguments as run time 
-Dhttp.proxyHost={host} -Dhttp.proxyPort={port}

**Comment by cdancy** [comment]
Closing as convo has gone stale. As there is a potential solution above I would suggest trying that.
