### ISSUE TITLE
Add View support

### ISSUE THREAD

**Issue by NoTranslation** [cdancy/jenkins-rest#123]
The methods in JobApi do not support views and nested views(Nested View Plugin)

### Expected Behavior
An extra paramater simillar to optionalFolderPath in the methods of JobApi that allows for the View path to passed in and parsed correctly

### Current Behavior
Setting the Jenkins Client endpoint directly to the Url + Viewpath works for some methods like buildInfo but not for other methods like build. This isn't how the JenkinsClient endpoint is supposed to be used aswell (As far as I can tell).

So jobs that are in nested views or views are unable to be triggered to build using the build method.

### Context
Have a jenkins server running with Jobs that are in nested views that are unable to be triggered to build using the library.
For e.g a job could be http://localhost:8080/view/team/Dev/job/test1

**Comment by NoTranslation** [comment]
Should I overload the api methods to add the extra parameters to insure backwards compatibility or add the param into the current method signatures

**Comment by cdancy** [comment]
@NoTranslation I would just add the param in and we can bump to the relevant version to denote a break in api.

**Comment by cdancy** [comment]
Closing as convo has gone stale. Feel free to re-open should you want to discuss further.
