### ISSUE TITLE
Add support for ChangeSet's in BuildInfo

### ISSUE THREAD

**Issue by ralfgrossklaus** [cdancy/jenkins-rest#127]
Hello!

We have the use case to access some of the information within the ChangeSets of a Build. For example Commiter information or Revisions that where included in this build. As the Jenkins REST API provides means to access this information, it would be nice to access it with this API too. So I would suggest extending the BuildInfo with the ChangeSet properties.

Regards, Ralf

PS: Sorry for first opening the Pull request

**Comment by cdancy** [comment]
@ralfgrossklaus no apologies necessary ... did you want to open a PR for this? That would be your quickest path to getting things merged.

**Comment by ralfgrossklaus** [comment]
Thanks for the quick answer. I reopened the PR
