### ISSUE TITLE
why there are only two workflow related api?

### ISSUE THREAD

**Issue by chingjustwe** [cdancy/jenkins-rest#137]
I came from [pipeline-stage-view-plugin](https://github.com/jenkinsci/pipeline-stage-view-plugin/tree/master/rest-api) and saw there are lots of existing restful apis, But I only find two of them in [JobApi](https://github.com/cdancy/jenkins-rest/blob/master/src/main/java/com/cdancy/jenkins/rest/features/JobsApi.java): **jobs:workflow** and **jobs:pipeline-node**, I have to write my own code if I need to get other workflow info like [Log of Pipeline Node](https://github.com/jenkinsci/pipeline-stage-view-plugin/tree/master/rest-api#get-jobjob-namerun-idexecutionnodenode-idwfapilog).

Is there any plan to include more **wfapi** please? and the ETA? thanks.

### Expected Behavior
N/A

### Current Behavior
N/A

### Context
N/A

### Steps to Reproduce (for bugs)
N/A

### Your Environment
Jenkins-Rest 0.0.27

**Comment by cdancy** [comment]
@chingjustwe this project is **entirely** community driven. If you'd like to see something just send in a PR!

**Comment by cdancy** [comment]
@chingjustwe closing. Feel free to re-open if you'd like to further discuss.
