### ISSUE TITLE
jobInfo returns null for jobs within a WorkflowMultiBranchProject type of job

### ISSUE THREAD

**Issue by 29jm** [cdancy/jenkins-rest#156]
I have a Jenkins job with `.clazz()` attribute `org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject`, and getting the `JobInfo`s of its children jobs doesn't work, returning `null`.

### Expected Behavior

If `folder1/folder2/multiJob` is a job with `.clazz()` attribute `org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject`, then it's (up to the `_class` attribute) similar to a folder and calling `jkApi.api().jobsApi().jobInfo("folder1/folder2/multiJob", "someBranch")` for instance should yield a normal `JobInfo` object.

### Current Behavior

`jkApi.api().jobsApi().jobInfo("folder1/folder2/multiJob", "someBranch")` returns `null`.

Also, trying to get the `JobInfo` of the multi branch job itself results in a `NullPointerException` because no `color` attribute is returned, the API responds with a folder structure, just with a different `_class`. This point is somewhat expected, the previous point is what the issue is about.

### Context

I'm trying to get information from all jobs in a folder, including those within a "multi branch" type of job.

### Steps to Reproduce (for bugs)

I can't really provide a project, as it requires a running jenkins instance with the specific type of job present, but given that, the following (kotlin) snippet will reproduce the issue:
```kotlin
fun main() {
    val jkApi = JenkinsClient.builder()
            // .endPoint("")
            // .credentials("")
            .build()
    val jobInfo = jkApi.api().jobsApi().jobInfo("root/project/multiBranchJob", "branchName")
    println("jobInfo == null ? ${jobInfo == null}")
}
```

### Your Environment

Jenkins v2.176.3

Thank you for reading, and for the library!

**Comment by cdancy** [comment]
Hello @29jm. You could put together a PR that reproduces the issues within a test. Are you interested in sending in a PR to fix this or looking for someone from the community to do so?

Can you also run things with debug/http-wire logging enabled to see what the returned output looks like? Just wondering if Jenkins itself is returning "nothing" or we're failing to parse something.

**Comment by 29jm** [comment]
Hi, thank you for the quick response. After double checking things on my end, I noticed I had the path wrong in my calls to `jobInfo` when using multi branch jobs... So this in fact works fine, sorry for the noise.

The only potential "issue" remaining is the `NullPointerException` when getting the `JobInfo` of a multi branch job (though that one doesn't bother me, I can just check the class attribute beforehand). I can file a new issue for that one if you want me to.

**Comment by cdancy** [comment]
>  I can file a new issue for that one if you want me to.

@29jm yeah please do and if you can send along the stracktrace as well as the http-wire logs that would be great. Let me know if you need getting either of those.

**Comment by 29jm** [comment]
@cdancy Will do!
