### ISSUE TITLE
Valid Certificate Error 

### ISSUE THREAD

**Issue by rohitranjan1991** [cdancy/jenkins-rest#165]
Certificate Error While connecting to Jenkins.

In additional to this, i am providing the token as "<user>:<token>" to the .token() menthod. 

### Expected Behavior
It should connect. 

### Current Behavior

Getting this response right now:

Unexpected exception being thrown: error=Error{context=null, message=sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target connecting to GET https://example.com/crumbIssuer/api/xml?xpath=concat%28//crumbRequestField,%22%3A%22,//crumb%29 HTTP/1.1, exceptionName=org.jclouds.http.HttpResponseException} connecting to HEAD https://example.com/ HTTP/1.1

---
@cdancy, Is there any way I can ask jenkins-rest to ignore the invalid certificate ? or any workaround?

**Comment by martinda** [comment]
Hi @rohitranjan1991 . Thanks for reporting this problem. In order for a fix to be made, the problem needs to be reproduced and a unit test written. The only way I know to do this is to capture the JSON or the HTTP response. Can you please use the instructions in the [wiki](https://github.com/cdancy/jenkins-rest/wiki) to enable HTTP Logging and share what you get here?

Note that at this time the master branch of this repo cannot be built until issue #142 is resolved.

I definitely won't have time to look at this until next week. Would you be able to send a pull-request?

**Comment by cdancy** [comment]
Lets close this issue as it seems to have gone stale. Feel free to re-open if you'd like to discuss further.
