### ISSUE TITLE
403 No valid crumb was included in the request

### ISSUE THREAD

**Issue by zkoalas** [cdancy/jenkins-rest#166]
when i use API update_job to update jenkins job, i find if i have chinese in config string ,the jenkins config.xml can't recognize correct chinese,but if i just update job by jenkins web,i will be work

So i guess it must be something wrong in http request, i try to use http request, and add header headers: { 'Content-Type': 'application/xml;charset=UTF-8' }
it works correct .

I look up the source code ,find the source code didn't add the charset type.

**Comment by martinda** [comment]
@zkoalas are you able to please send a pull-request?

**Comment by FurmigaHumana** [comment]
I am also with this issue

HTTP ERROR 403 No valid crumb was included in the request

**Comment by zhigang0309** [comment]
> 

这个问题解决了吗

**Comment by martinda** [comment]
The no valid crumb issue is already tracked in #169.

**Comment by cdancy** [comment]
Lets close this as it's already being tracked.
