### ISSUE TITLE
how to stop a build

### ISSUE THREAD

**Issue by Fick707** [cdancy/jenkins-rest#188]
Sometimes we want to abort a running build. 
How to do so via the REST api ?

**Comment by martinda** [comment]
Currently I don't see an API in the jenkins-rest for aborting a build. But there is an API for it in the [Jenkins documentation](https://www.jenkins.io/doc/book/using/aborting-a-build/) , care to send a pull-request?

**Comment by Fick707** [comment]
> 

Yeah,I have implemented this function temporarily, by add the following line in src/main/java/com/cdancy/jenkins/rest/features/JobsApi.java 


    @Named("jobs:stop-build")
    @Path("{optionalFolderPath}job/{name}/{number}/stop")
    @ResponseParser(RequestStatusParser.class)
    @Consumes(MediaType.WILDCARD)
    @POST
    RequestStatus stopBuild(@Nullable @PathParam("optionalFolderPath") @ParamParser(OptionalFolderPathParser.class) String optionalFolderPath,
                            @PathParam("name") String jobName,
                            @PathParam("number") int buildNumber);

**Comment by Fick707** [comment]
> Currently I don't see an API in the jenkins-rest for aborting a build. But there is an API for it in the [Jenkins documentation](https://www.jenkins.io/doc/book/using/aborting-a-build/) , care to send a pull-request?

I have sent a pull request for this issue.
