### ISSUE TITLE
Error 403 No valid crumb was included in the request

### ISSUE THREAD

**Issue by zhigang0309** [cdancy/jenkins-rest#189]

**Comment by cdancy** [comment]
@martinda I believe has a fix for this if I'm not mistaken.

**Comment by martinda** [comment]
Yes I have a fix. There are a few problems to solve before I can send a PR for my fix.

**Comment by martinda** [comment]
The problems that need to be solved are in #191 , they are not that hard to fix but would required a new minimum Jenkins version to be used in testing, which might have other consequences.

**Comment by martinda** [comment]
This is already tracked in #169
