### ISSUE TITLE
optionalFolderPath to take simple path expression also.

### ISSUE THREAD

**Issue by Dhivyaa21** [cdancy/jenkins-rest#21]
I am trying to make the JobsAPI's optionalFolderPath to accept simple path expression like 
"folder1/folder2". In the code below, is it possible to access the request's `@pathparams`  values from within the filter method during runtime, so we could check if each name is preceded by `/job`, if not then append it?

https://github.com/cdancy/jenkins-rest/blob/cb7fbd54afe44fd0713b6f06f168a9db41483af4/src/main/java/com/cdancy/jenkins/rest/filters/ScrubNullFolderParam.java#L34-L38

**Comment by cdancy** [comment]
@Dhivyaa21 yeah the `httpRequest` reference has everything you need. Feel free to send in a PR with an impl as I think this would be a welcome addition.

**Comment by martinda** [comment]
Should this feature account for the following strange cases:
- Path expression starting with a slash (`/**`)
- Two or more slashes in a row at start, middle or end (`//**`, `**//**`, `**//`)
- Path expression ending with slash (`**/`)
Should the feature attempt to correct these, or return an error?

**Comment by cdancy** [comment]
Agreed unless there is a reason I'm not thinking of. If were in agreement lets make sure we have tests to cover these use-cases as well.

Thanks for looking into things @martinda

**Comment by cdancy** [comment]
Closing as this functionality has been merged with #22
