### ISSUE TITLE
how to user JenkinsClinet api manage nodes

### ISSUE THREAD

**Issue by duhuangwen** [cdancy/jenkins-rest#220]

**Comment by cdancy** [comment]
@duhuangwen I don't think we have that feature implemented yet.

**Comment by martinda** [comment]
A workaround exists. A configuration-as-code file can be uploaded to configure a node. The details of that configuration-as-code file would be for you to compose. I suggest  that you configure Jenkins with a node manually through the UI, then you can view or download the casc yml file via the UI to study how it work, then use this library to upload casc.yml files.

This library does support configuration-as-code. Please see the [ConfigurationAsCodeApi.java](https://github.com/cdancy/jenkins-rest/blob/39eec3af120394ef73773d2ab24f7fcd0818478e/src/main/java/com/cdancy/jenkins/rest/features/ConfigurationAsCodeApi.java) and [its tests](https://github.com/cdancy/jenkins-rest/blob/39eec3af120394ef73773d2ab24f7fcd0818478e/src/test/java/com/cdancy/jenkins/rest/features/ConfigurationAsCodeApiLiveTest.java) for examples on how to use it.

**Comment by duhuangwen** [comment]
@martinda Thank you for your help, your suggestion is useful and I have solved it
