### ISSUE TITLE
Plugin dependency issue in current docker jenkins version

### ISSUE THREAD

**Issue by martinda** [cdancy/jenkins-rest#222]
The current docker image calls for jenkins 2.277.4-jdk11. When running this version, I get the following error:

```
Sending build context to Docker daemon   7.68kB
Step 1/6 : ARG jenkins_tag=2.277.4-jdk11
Step 2/6 : FROM jenkins/jenkins:$jenkins_tag
 ---> 9d90b56f1a78
Step 3/6 : COPY --chown=jenkins:jenkins init.groovy.d/ /usr/share/jenkins/ref/init.groovy.d/
 ---> d3cb7ae342be
Step 4/6 : COPY --chown=jenkins:jenkins plugins.yml /usr/share/jenkins/ref/plugins.yml
 ---> 432d6654a0be
Step 5/6 : RUN jenkins-plugin-cli -f /usr/share/jenkins/ref/plugins.yml
 ---> Running in 6314274b56fe
Multiple plugin prerequisites not met:
Plugin workflow-aggregator:2.6 depends on cloudbees-folder:6.708.ve61636eb_65a_5,
but there is an older version defined on the top level - cloudbees-folder:6.17
```

See [this community discussion](https://community.jenkins.io/t/jenkins-docker-issue-multiple-plugin-prerequisites-not-met/1586) for additional details.

Upgrading to 2.335-jdk11 appears to fix the problem. I am preparing a pull-request.

**Comment by martinda** [comment]
Two other solutions exist to make the image build again:

* Use `--latest false` with the plugin manager in the Dockerfile.
* List all the plugin version in plugins.yml

However doing so I ran into another issue: https://issues.jenkins.io/browse/JENKINS-67848

**Comment by martinda** [comment]
A solution came from the [community discussion](https://community.jenkins.io/t/jenkins-docker-issue-multiple-plugin-prerequisites-not-met/1586).

The solution is to list all the plugins and their versions. This presents a new challenge, that of establishing a procedure for refreshing the list of plugins for the docker image used by the live tests.

**Comment by martinda** [comment]
Another solution is to remove the versions in the list of plugins and let the Jenkins plugin dependency resolution algorithm pick the latest compatible versions for all plugins. This has the drawback of being non-reproducible.

I am choosing this solution as it is the simplest one to implement.

**Comment by cdancy** [comment]
Merged relevant PR.
