### ISSUE TITLE
Wiki - offer

### ISSUE THREAD

**Issue by martinda** [cdancy/jenkins-rest#23]
I did more work on the Wiki and I was wondering if you'd be interested in rolling it in to upstream. It contains pretty much what I wanted to capture so far. It is [here](https://github.com/martinda/jenkins-rest/wiki).

I do not know how to open a PR for this though. It may not even be possible.

**Comment by cdancy** [comment]
@martinda I've added you as a collaborator to this project which will give you access to all the bells and whistles to do what you need. You've been a great help thus far and put new life back into this project.

Feel free to update the wiki here as you see fit.

With respect to code I would ask that you, and I'll abide by this rule as well, do not push directly to master and instead create PR's in the usual sense and be sure to tag the other individual (that being myself as it's only us at this point).

With that said: thanks again and welcome aboard!

**Comment by martinda** [comment]
Thanks @cdancy . Yes will use continue to follow the usual pull-request flow for doing work. I am hoping to have time to continue the wiki soon!

**Comment by cdancy** [comment]
@martinda and if I didn't already say so before: the wiki looks good to me ;)

**Comment by martinda** [comment]
@cdancy thank you. I could not find a pull-request flow for the wiki, so I just pushed it. I think this issue can be closed.

**Comment by cdancy** [comment]
Yeah I poked around as well, and while there are solutions, they feel a bit cumbersome.
