### ISSUE TITLE
jenkins-rest not compilable with jcloud

### ISSUE THREAD

**Issue by likaer** [cdancy/jenkins-rest#31]
Here is the version

        <dependency>
            <groupId>com.cdancy</groupId>
            <artifactId>jenkins-rest</artifactId>
            <version>0.0.13</version>
        </dependency>

when I run with this, I got this errors, see[jcloud](https://stackoverflow.com/questions/39615376/apache-jclouds-java-lang-nosuchmethoderror-when-using-rackspace-in-a-spring-boot) for more info

```org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jenkinsService': Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.<init>(Lcom/google/gson/internal/ConstructorConstructor;Lcom/google/gson/FieldNamingStrategy;Lcom/google/gson/internal/Excluder;)V```

**Comment by cdancy** [comment]
@likaer try using the shaded classifier and let me know how that works out.

**Comment by cdancy** [comment]
@likaer it's a known issue with jclouds, which we use in the backend here, in that they depend on an older version of gson. There is an open JIRA issue where they are currently attempting to tackle this but until then you should be able to get around this by using the `shaded` classifier which bundles all deps into a single jar.

**Comment by cdancy** [comment]
My apologies: it's the `all` classifier and NOT shaded.

**Comment by likaer** [comment]
Fine, I get it work now.

`
        <dependency>
            <groupId>com.cdancy</groupId>
            <artifactId>jenkins-rest</artifactId>
            <version>0.0.13</version>
            <classifier>all</classifier>
        </dependency>
`

**Comment by cdancy** [comment]
@likaer awesome. Closing this issue then. Feel free to re-open should you have anymore questions.
