### ISSUE TITLE
HttpResponseException

### ISSUE THREAD

**Issue by hcray** [cdancy/jenkins-rest#32]
code:
    boolean ret = JenkinsClient.builder()
                .endPoint("http://10.1.1.44:8080/jenkins") // Optional. Defaults to http://127.0.0.1:8080
                .credentials("MjE4MjklM0FhYmNAMTIzNA==") // Optional.
                .build()
                .api().jobsApi().enable(null, "BER");

debug info:

SystemInfo{errors=[Error{context=null, message=Null message connecting to HEAD http://10.1.1.44:8080/jenkins/ 
HTTP/1.1, exceptionName=org.jclouds.http.HttpResponseException}],
 hudsonVersion=-1, jenkinsVersion=-1, jenkinsSession=-1, instanceIdentity=-1, sshEndpoint=-1, server=-1}

wireshark show:
GET /jenkins/crumbIssuer/api/xml?xpath=concat%28//crumbRequestField,%22%3A%22,//crumb%29 HTTP/1.1
Accept: text/plain
Authorization: Basic MjE4MjklM0FhYmNAMTIzNA==
User-Agent: jclouds/2.1.1 java/1.8.0_131
Host: 10.1.1.44:8080
Connection: keep-alive

<html><head><title>Apache Tomcat/7.0.70 - Error report</title><style></style> </head><body><h1>HTTP Status 401 - Malformed HTTP basic Authorization header</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>Malformed HTTP basic Authorization header</u></p><p><b>description</b> <u>This request requires HTTP authentication.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.70</h3></body></html>

**Comment by cdancy** [comment]
When I try to decode your auth I get `21829%3Aabc@1234` which is not valid. Decoding _should_ produce a string that looks like `username:password` (note the colon delimiter in the middle).
