### ISSUE TITLE
The StageFlowNode is missing the ID field, which causes the corresponding NodeId field to be missing when calling the JobsApi.pipelineNodeLog() method

### ISSUE THREAD

**Issue by kun303-cloud** [cdancy/jenkins-rest#360]
The ID is missing here, which makes this method uncallable
![image](https://github.com/user-attachments/assets/ad3b745d-b465-4930-8644-7173435be62a)

**Comment by kun303-cloud** [comment]
@cdancy  Is this a problem? If yes, I'd like to deal with it, is that okay

**Comment by cdancy** [comment]
@kun303-cloud feel free to fix things up and send out a PR!
