### ISSUE TITLE
java.lang.NoSuchMethodError: com.google.common.collect.Maps.toMap while using latest jar

### ISSUE THREAD

**Issue by Shashank-Ramesh** [cdancy/jenkins-rest#37]
Jenkins rest library throws the below error while using in a maven project. 

14:54:51 FATAL: com.google.common.collect.Maps.toMap(Ljava/lang/Iterable;Lcom/google/common/base/Function;)Lcom/google/common/collect/ImmutableMap;
14:54:51 java.lang.NoSuchMethodError: com.google.common.collect.Maps.toMap(Ljava/lang/Iterable;Lcom/google/common/base/Function;)Lcom/google/common/collect/ImmutableMap;
14:54:51 	at org.jclouds.functions.ExpandProperties.apply(ExpandProperties.java:46)
14:54:51 	at org.jclouds.ContextBuilder.buildInjector(ContextBuilder.java:319)
14:54:51 	at org.jclouds.ContextBuilder.buildApi(ContextBuilder.java:651)
14:54:51 	at org.jclouds.ContextBuilder.buildApi(ContextBuilder.java:643)
14:54:51 	at com.cdancy.jenkins.rest.JenkinsClient.createApi(JenkinsClient.java:85)
14:54:51 	at com.cdancy.jenkins.rest.JenkinsClient.<init>(JenkinsClient.java:72)
14:54:51 	at com.cdancy.jenkins.rest.JenkinsClient$Builder.build(JenkinsClient.java:220)
14:54:51 	at org.adasci.plugins.developmentGate.loadbalancer.utils.HttpUtility.sendBuildWithParametersCall(HttpUtility.java:134)
14:54:51 	at org.adasci.plugins.developmentGate.loadbalancer.LoadBalancerBuilder.perform(LoadBalancerBuilder.java:68)
14:54:51 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
14:54:51 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
14:54:51 	at hudson.model.Build$BuildExecution.build(Build.java:205)
14:54:51 	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
14:54:51 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
14:54:51 	at hudson.model.Run.execute(Run.java:1720)
14:54:51 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
14:54:51 	at hudson.model.ResourceController.execute(ResourceController.java:98)
14:54:51 	at hudson.model.Executor.run(Executor.java:404)
14:54:51 Finished: FAILURE

**Comment by cdancy** [comment]
@Shashank-Ramesh yeah it's a known issue in that a dependency of this library depends on a newer version of guava. Try using the `all` classifier for this library when specifying your deps and you should be good to go.

**Comment by Shashank-Ramesh** [comment]
@cdancy : Thanks for your quick response. This worked :) I can close this ticket, but have few more questions which I can probably use this thread for.
1. On successful login to Jenkins server , is there a way to get some authentication token which I can use for further logins. I would definitely avoid send multiple login requests from REST api, if already logged in
2. I noticed an implementation for Statistics API, but this gives empty results. Am i missing something?
3. I would need details on Nodes . Straight forward use case, I would need available executors of all nodes assigned to a Label. Would I get such information or do I have to write something custom

**Comment by cdancy** [comment]
For #1 you shouldn't need to worry about this as long as you're using the same create instance of this library.

For #2 can you provide a snippet of what you're doing?

For #3 I don't believe we've coded anything for querying the nodes but would be happy to do so. Can you point us to the REST Api documentation or maybe you'd like to send in a PR? This library is almost entirely community driven so we'd be happy to accept a PR.
