### ISSUE TITLE
com.cdancy.jenkins.rest.shaded.org.jclouds.rest.AuthorizationException on fetching BuildInfo

### ISSUE THREAD

**Issue by Shashank-Ramesh** [cdancy/jenkins-rest#39]
We have a scenario where we trigger build and keep waiting until build ends. For this, we have written a poll mechanism which keep fetching BuildInfo every time, but this fails the first call itself throwing Auth exception error. What I dont understand is , credentials used are the same. 
Am I missing something?

**Comment by martinda** [comment]
Hi @Shashank-Ramesh Can you share the code? I remember seeing cases like that, but it was so few that I do not remember. Are you following the same code as in the [wiki example](https://raw.githubusercontent.com/wiki/cdancy/jenkins-rest/tracking-builds/RunningABuild.groovy)?

**Comment by Shashank-Ramesh** [comment]
Hi @martinda , yes I am using similar approach . PFB the methods : 

After Build with parameters call, Poll job status call is made. But for some reason Auth exception has become more frequent now
----------------------------------------------------------------------------------------------------------------
public IntegerResponse sendBuildWithParametersCall(JobsApi jobsApi, BuildListener listener,
			Buildservicedata buildServiceData, BuildServiceWorkers assignedWorker, AbstractBuild<?, ?> build)
			throws DevelopmentGatePluginException,InterruptedException {

		IntegerResponse response = null;
		
		boolean isAuthError = false;
		
		org.adasci.plugins.developmentGate.loadbalancer.LoadBalancerBuilder.DescriptorImpl descriptorLoadBalancer;
		descriptorLoadBalancer = Jenkins.getInstance().getDescriptorByType(
				org.adasci.plugins.developmentGate.loadbalancer.LoadBalancerBuilder.DescriptorImpl.class);
		
		int retryInterval = Integer.parseInt(descriptorLoadBalancer.getRetryInterval()); 
		
		RetryOnException retry = RetryOnException.getRetryOnExceptionObject(noOfRetry);

		ConsolePrinter.printInfo(listener, "\nTriggering build...");

		response = jobsApi.buildWithParameters(null, jobName, urlParams);

		while (response == null) {

			ConsolePrinter.printWarning(listener, "Build trigger failed , retrying...");

			response = jobsApi.buildWithParameters(null, jobName, urlParams);
		
			Thread.sleep(retryInterval);
		}

		while (response.errors().size() > 0) {
			
			for (Error error : response.errors()) {
				
				ConsolePrinter.printWarning(listener, "\nException on fetching response : "+error.message());
				
				if (error.message().contains("AuthorizationException") ) {
					
					isAuthError = true;
					
					retry.errorOccured(); // Going to retry
					
					ConsolePrinter.printWarning(listener, "\nException in connecting to remote jenkins server, Retrying...");
					
					response = jobsApi.buildWithParameters(null, jobName, urlParams);
					
				}else{
					isAuthError = false;
					break;
				}
			}
			
			if(!isAuthError){
				throw new DevelopmentGatePluginException("Worker assignment failed, please contact Administrator!");
			}
		} 
		
		ConsolePrinter.printSuccess(listener, "\nBuild triggered succesfully!");

		return response;
	}

public static String pollWorkerJobStatus(int queueId, JenkinsClient client, String jobName,
			BuildListener listener) throws DevelopmentGatePluginException{

		String status = "";
		
		org.adasci.plugins.developmentGate.loadbalancer.LoadBalancerBuilder.DescriptorImpl descriptorLoadBalancer;
		descriptorLoadBalancer = Jenkins.getInstance().getDescriptorByType(
				org.adasci.plugins.developmentGate.loadbalancer.LoadBalancerBuilder.DescriptorImpl.class);
		
		int retryInterval = Integer.parseInt(descriptorLoadBalancer.getRetryInterval());
		String retryCount = descriptorLoadBalancer.getNoOfRetry();

		try {
			
			RetryOnException retry = RetryOnException.getRetryOnExceptionObject(retryCount);

			QueueItem queueItem = null;
			
			BuildInfo buildInfo = null;
			
			while( queueItem == null || buildInfo == null ){
				
				try{
					if( queueItem == null )
						queueItem = client.api().queueApi().queueItem(queueId);
					
					buildInfo = client.api().jobsApi().buildInfo(null, jobName, queueItem.executable().number());
					
					break;
				}
				
				catch (AuthorizationException e ){
					
					e.printStackTrace();
					
					retry.errorOccured();
					
					ConsolePrinter.printWarning(listener, "\nException in connecting to remote jenkins server, Retrying...");
					
					Thread.sleep(retryInterval*2000);
					
					continue;
				}
			}
			
			// Get the build info of the queue item being built and poll until
			//it is done
			
			retry = RetryOnException.getRetryOnExceptionObject(retryCount);
			
			while (buildInfo.building()) {
				
				Thread.sleep(retryInterval*2000);
				
				try{
					buildInfo = client.api().jobsApi().buildInfo(null, jobName, queueItem.executable().number());
				} catch (AuthorizationException e ){
					
					e.printStackTrace();
					
					retry.errorOccured();
					
					ConsolePrinter.printWarning(listener, "\nException in connecting to remote jenkins server, Retrying...");
					
					continue;
				}
			}

			//ConsolePrinter.printInfo(listener, "Build status: " + buildInfo.result());

			status = buildInfo.result();

		} catch (InterruptedException e) {
			e.printStackTrace();
			throw new DevelopmentGatePluginException("Error fetching Job status : "+e.getMessage());
		}

		return status;

	}

--------------------------------------------------------------------------------------------------------------

**Comment by cdancy** [comment]
Closing this issue as there hasn't been any convo for quite some time. Feel free to re-open if necessary.

**Comment by ginajsalib** [comment]
I am facing the same issue using Jenkins API with a token of an LDAP user. Is there any fix other than using non-LDAP user?
