### ISSUE TITLE
com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.<init>

### ISSUE THREAD

**Issue by peter527** [cdancy/jenkins-rest#40]
### Current Behavior

```
dispatch failed; nested exception is java.lang.NoSuchMethodError: com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.<init>(Lcom/google/gson/internal/ConstructorConstructor;Lcom/google/gson/FieldNamingStrategy;Lcom/google/gson/internal/Excluder;)V] with root cause
java.lang.NoSuchMethodError: com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.<init>(Lcom/google/gson/internal/ConstructorConstructor;Lcom/google/gson/FieldNamingStrategy;Lcom/google/gson/internal/Excluder;)V
	at org.jclouds.json.internal.DeserializationConstructorAndReflectiveTypeAdapterFactory.<init>(DeserializationConstructorAndReflectiveTypeAdapterFactory.java:118)
	at org.jclouds.json.config.GsonModule.provideGson(GsonModule.java:130)
```

### Your Environment

I met some problems when i use it in a spring boot2.0 project

**Comment by cdancy** [comment]
Try using the _all_ classifier. 

This is a known issue with this library, and specifically jclouds, using an older version of gson.

**Comment by cdancy** [comment]
Closing issue. Feel free to re-open should using the `all` classifier not work.

**Comment by solankivaibhav789** [comment]
I have the same issue. I also add all classifier than also it does not work. please give me a proper solution.

**Comment by cdancy** [comment]
Use the all classifier and make sure to exclude all transitive deps.

**Comment by solankivaibhav789** [comment]
`<dependency>
			<groupId>com.cdancy</groupId>
			<artifactId>jenkins-rest</artifactId>
			<version>0.0.18</version>
			<classifier>all</classifier>
		</dependency>`

If I use this then it will download the file as the following screenshot so It did not resolve the dependency problem.
![image](https://user-images.githubusercontent.com/20421401/56359827-53fb2200-6200-11e9-886a-8e31808760ae.png)

**Comment by jiotiG** [comment]
For Spring Boot 2.0 I was facing the same exception, excluding the transitive dependencies excluded everything which was important so nothing was working. 
I had to pin the gson to an older version to fix
`      force 'com.google.code.gson:gson:2.5'      `

**Comment by blajoie55** [comment]
I got around this by using the classifier `all` in my build.gradle like so: `compile "com.cdancy:jenkins-rest:0.0.23:all"`
