### ISSUE TITLE
Trigger parameterized job with null parameters

### ISSUE THREAD

**Issue by Dhivyaa21** [cdancy/jenkins-rest#42]
### Expected Behavior
Trigger a build successfully for a parameterized job with no parameters using buildWithParameters API

### Current Behavior
buildWithParameters Api throws an exception for null or empty parameters in the method blow. I think we may have to allow null values for params and handle it in the BindMapToForm class.
https://github.com/cdancy/jenkins-rest/blob/359dd0461330e6f620caa9981550f3e4ba5ce5f2/src/main/java/com/cdancy/jenkins/rest/features/JobsApi.java#L161-L169

**Comment by cdancy** [comment]
@Dhivyaa21 so is the value of your key null or empty or potentially both? Have you tried using an empty list for the value to see if that works?

**Comment by Dhivyaa21** [comment]
My use case is to trigger a build with no parameters (say I want to use the default values of the parameters in the job config) for a parameterized job.  When I passed null (or an empty map) to the buildWithParameters API, It throws an exception as shown below.

https://github.com/cdancy/jenkins-rest/blob/359dd0461330e6f620caa9981550f3e4ba5ce5f2/src/main/java/com/cdancy/jenkins/rest/binders/BindMapToForm.java#L37-L39

**Comment by cdancy** [comment]
Gotcha. Can you just use [THIS](https://github.com/cdancy/jenkins-rest/blob/359dd0461330e6f620caa9981550f3e4ba5ce5f2/src/main/java/com/cdancy/jenkins/rest/features/JobsApi.java#L158) api call if you're not building with parameters? Does the job accept parameters?

**Comment by Dhivyaa21** [comment]
`build` API works only for non parameterized jobs. I tried using the build API and got back a HTTP 400.

**Comment by cdancy** [comment]
Ok I gotcha. So you've got a parameterized build but just don't want to override any params. That makes sense and seems silly that we are not allowing for it. Care to send in a PR to fix this?

**Comment by Dhivyaa21** [comment]
Sure I can send a PR.

**Comment by cdancy** [comment]
Thanks!

**Comment by Dhivyaa21** [comment]
@cdancy @martinda Is it possible to release this change?

**Comment by cdancy** [comment]
@Dhivyaa21 can definitely put out a new point release just had one last minute comment on the PR itself. Does it feel weird that we can pass in a null map but fail on an empty map? Seems like both should be allowed.

**Comment by Dhivyaa21** [comment]
@cdancy - Yes. We missed it. I will send the changes in another pull-request.

**Comment by cdancy** [comment]
@Dhivyaa21 version `0.0.16` has been released. Due to an oversight there will be no version `0.0.15` so apologies for any confusion in that regard.
