### ISSUE TITLE
Is it ok to support jdk 7?

### ISSUE THREAD

**Issue by iapplejohn** [cdancy/jenkins-rest#45]
The systems are built based on jdk 7 in my company, it's not easy to upgrade to jdk 8, is it ok to release versions utilizing jdk 7?

**Comment by cdancy** [comment]
@iapplejohn so JDK7 has been eol for quite sometime now and while I understand your problem (faced similar issue not too long ago here and it was a MASSIVE pain in the butt) releasing a jdk7 version of this plugin I don't believe is easily possible. The underlying libraries we depend on I believe require jdk8. If you want to try building this locally, and switch to using jdk7, and see if things work I'd be interested and might provide the example we need to confirm it actually does work.

**Comment by cdancy** [comment]
Closing this issue. Feel free to re-open if you'd like to continue further conversation.
