### ISSUE TITLE
Standardize on single value wrapper

### ISSUE THREAD

**Issue by cdancy** [cdancy/jenkins-rest#47]
When an endpoint returns a single value (e.g. String or an Integer or something else) we wrap that in a IntegerResponse (or whatever is appropriate for the type). I believe we can do better by using a generic wrapper with types. Something like: `Primitive<String>` or `JValue<String>` or maybe `JPrimitive<String>`. Just throwing out some ideas but we should do something.

@martinda I know we've talked about this before but I'd like to jump in and attempt a proper fix just not sure what fits best. Now that some time has passed from previous conversations do you have any updated thoughts/opinions/ideas?

**Comment by martinda** [comment]
Interesting concept. What is the benefit?

**Comment by cdancy** [comment]
I must be getting missed emails or something as I'm not getting notified of these updates. In either event the general idea would be to have a single wrapper around endpoints that return a single value. Instead of an `IntegerResponse` or `StringResponse` or `BooleanResponse` we'd just have a single `JValue` (or whatever we want to use) which is typed (e.g. JValue<String>) to include whatever it is holding. It would simplify things IMO and I've done similar things with the `bitbucket-rest` client though this client has loads more single values due to the responses not always coming back in json format.

**Comment by martinda** [comment]
@cdancy Sounds cool!
