### ISSUE TITLE
[Question] buildWithParameters functionality

### ISSUE THREAD

**Issue by damian-t** [cdancy/jenkins-rest#50]
I would like to trigger a parametrized build using this library but somehow the parameters are not sent in the request. I have defined an authentication token in the job (trigger by `jenkinsServer/job/jobName/buildWithParameters?token=TOKEN`) and want to set two parameters to `param1=param1value` and `param2=param2value`.

Instead of sending the set parameters, the following code triggers the build with the default parameter values (specified in the jenkins configuration).

```
// set up client
JenkinsClient client = JenkinsClient.builder()
    .endPoint(jenkinsServer)
    .credentials(Base64encodedCredentials).build();

// set parameters
Map<String, List<String>> params = new HashMap<>();
List<String> tokenList = new ArrayList<>();
List<String> paramList1 = new ArrayList<>();
List<String> paramList2 = new ArrayList<>();
tokenList.add(TOKEN);
paramList1.add(param1value);
paramList2.add(param2value);
params.put("token", tokenList);
params.put("param1", param1List);
params.put("param2", param2List);

// sending request
IntegerResponse response = client.api().jobsApi()
        .buildWithParameters(null, jobName, params);
```

**Comment by cdancy** [comment]
When the request is sent over it's done as form params and not query params which is why you're not seeing the `token=` param getting passed. Is that where things are failing?

**Comment by damian-t** [comment]
The job itself is not failing, it is just ignoring the parameters of the request. While debugging, I looked at the `GeneratedHttpRequest` object. Method is "POST", URI is: `jenkinsServer/job/jobName/buildWithParameters`, with  payload-content: `"param2=param2value&param1=param1value&token=TOKEN"`.
To me, this looks more like query params actually..
Moreover, I believe the _order_ of query params is important. When I use curl to send the request (with token not immediately following _buildWithParameters_, the other parameters are also ignored.

**Comment by cdancy** [comment]
hmmm ... what happens when you leave out `token`?

**Comment by damian-t** [comment]
This does indeed work.. weird. What's the point then of configuring the token in the first place?

**Comment by cdancy** [comment]
So `token` is meant to be passed in as a query parameter and not a form parameter. It's a way of authenticating but we already provide a means of doing that when you build the client so it shouldn't be necessary.
```
JenkinsClient client = JenkinsClient.builder()
    .endPoint(jenkinsServer) 
    .credentials(Base64encodedCredentials).build(); // token should not be needed if this is provided
```

**Comment by isker** [comment]
@cdancy I ran into this problem myself in #62.  I don't think either of the forms of authentication on `JenkinsClient.Builder` are substitutes for the `token` query parameter.  The query parameter is a per-job authentication mechanism, whereas the Bearer/Basic auth mechanisms on JenkinsClient are for global access.  You can't use the per-job token in either of these cases.

See examples on https://wiki.jenkins.io/display/JENKINS/Authenticating+scripted+clients for its usage or the python jenkinsapi job invocation method https://github.com/pycontribs/jenkinsapi/blob/6d3bf94b34a521955dbb82c5ae7c2eba031af894/jenkinsapi/job.py#L175-L184

**Comment by shanmukakondaveti** [comment]
hii,i need to check status whether the job build  is success or failed,can anyone post the required code to check job status
