### ISSUE TITLE
How do I build jobs using jenkins oauth?

### ISSUE THREAD

**Issue by mingoooook** [cdancy/jenkins-rest#55]
I am using Github Oauth in jenkins.
How Can I build jobs in this case?

**Comment by cdancy** [comment]
@mingoooook I don't understand what you're asking in this context. Maybe [THIS](https://github.com/jenkinsci/github-oauth-plugin) is what you're looking for?

**Comment by mingoooook** [comment]
I solved it myselft.
That is credentials.
```
String credentilas = "username" + ":" + "api token";
JenkinsClient.builder()
                .credentials(credentils)
                .build();
```
