### ISSUE TITLE
[Question] Is it possible to get a list of commits for a specific branch in a repo?

### ISSUE THREAD

**Issue by bhavik3jain** [cdancy/jenkins-rest#58]
The title pretty much asks the question. 

I am currently trying to create a script, but that requires that I get a list of commits from a repo, but for a specific branch. I tried many different approaches, but was unable to get anywhere. If anyone could give me a pointer it will be very much appreciated.

**Comment by cdancy** [comment]
Did you mean to ask on this project `jenkins-rest` or on its sister project `bitbucket-rest`?

**Comment by bhavik3jain** [comment]
I am so sorry, I meant to do it on bitbucket-rest. I will close this and reopen on the other project.
