### ISSUE TITLE
do we support authentication by header content?

### ISSUE THREAD

**Issue by tshasc** [cdancy/jenkins-rest#59]
### Expected Behavior
My Jenkins server do authentication with header content, I wonder whether we support that

### Current Behavior
seems we just support authentication by username/passwd and property

**Comment by cdancy** [comment]
What do you mean? All credentials get sent to the server through a header. Both basic with and bearer are supported. Did you have something else in mind?

**Comment by martinda** [comment]
Actually, for Jenkins only Basic and Base64 encoded are supported by Jenkins itself. There is no Bearer token in Jenkins (there is in Bitbucket).

**Comment by tshasc** [comment]
Sorry that I didn't say it clearly.
We have another lay of authentication on top of jenkins which need "TOKEN: *****" in the header, then how should I instantiate a Jenkins Client so that it can pass the verification

**Comment by martinda** [comment]
Sounds like there is some kind of authentication layer between jenkins and the client. According to Stackoverflow, there is a way to [customize the Apache jclouds header](https://stackoverflow.com/questions/22853557/how-to-set-http-header-in-apache-jclouds). At this point I am not sure if this would require changes to the [JenkinsClient.java](https://github.com/cdancy/jenkins-rest/blob/master/src/main/java/com/cdancy/jenkins/rest/JenkinsClient.java).

**Comment by martinda** [comment]
You may also want to read [Authenticating scripted clients](https://wiki.jenkins.io/display/JENKINS/Authenticating+scripted+clients) on the Jenkins wiki.

**Comment by cdancy** [comment]
Yeah I've never heard of a `TOKEN` header unless there is some misunderstanding on your end. It may be a custom auth layer as martin noted.

**Comment by tshasc** [comment]
I know how to use httpClient for my request for sure.
But I wonder whether jenkins-rest can support such kind of scenarios?

TOKEN here is just an example which means there is a custom authentication layer which
need something inside the request header

**Comment by cdancy** [comment]
we could certainly wire something up for sure. maybe a 1-to-1 mapping of header to value but it would be very basic and couldn't support anything more than that.

**Comment by tshasc** [comment]
if u can provide the function to hide a header name/header value mapping in http request when using your client API then it should work for me.
I wish the http request can 1) pass our internal authentication with the content in the header
                                              2) talk to jenkins server which can do basic jenkins access

**Comment by cdancy** [comment]
@tshasc would you be interested in sending in a PR for this? We could expose an optional `headers(String, String)` parameter on the client builder that we would then in turn pass along to all invocations. That should do the trick and allow folks to supply whatever they need.

**Comment by cdancy** [comment]
Closing this ISSUE as it hasn't gotten any further response. Feel free to re-open if you'd like to continue the convo.
