### ISSUE TITLE
[Question] buildWithParameters usage

### ISSUE THREAD

**Issue by martinda** [cdancy/jenkins-rest#6]
It is not clear to my why the `buildWithParameters()` method in [JobsApi.java](https://github.com/cdancy/jenkins-rest/blob/master/src/main/java/com/cdancy/jenkins/rest/features/JobsApi.java#L153) takes a map of lists as the second argument:
```java
   Integer buildWithParameters(@PathParam("name") String jobName,
            @BinderParam(BindMapToForm.class) Map<String, List<String>> properties);
```
I would expect `Map<String, String>`. Why is the parameter value a list?

**Comment by cdancy** [comment]
@martinda because you're allowed to pass in something like `?foo=bar,bar1,bar2&animal=bear`. The value part of the parameter can have multiple values for better/worse.

**Comment by cdancy** [comment]
The above is for query parameters but the same applies here for form parameters. They can have multiple values attached to a single key.
