### ISSUE TITLE
Expose Pipeline REST API

### ISSUE THREAD

**Issue by choweiyuan** [cdancy/jenkins-rest#60]
### Expected Behavior

I'd like to poll my pipeline's stages status rather than overall build status. The API is here
https://github.com/jenkinsci/pipeline-stage-view-plugin/tree/master/rest-api 
more specifically 
https://github.com/jenkinsci/pipeline-stage-view-plugin/tree/master/rest-api#get-jobjob-namerun-idwfapidescribe

### Current Behavior

This API is currently not available in this library as far as I can tell. This'll help us get more information of the build's status, drill down to stages level.

**Comment by cdancy** [comment]
@choweiyuan just getting around to this now as I was at Dockercon last week and still catching up on things. It indeed would be great to have this. Care to send in a PR to get started on this work? Think it would be a great addition.

**Comment by cdancy** [comment]
Close as PR has been merged.
