### ISSUE TITLE
buildWithParameters usage

### ISSUE THREAD

**Issue by liuzhi-vip** [cdancy/jenkins-rest#61]
How do I add file parameters

**Comment by cdancy** [comment]
What exactly are you trying to do?

**Comment by liuzhi-vip** [comment]
buildWithParameters 
How does this method upload a JPG file or other type of file

**Comment by cdancy** [comment]
In a jenkins build you can specify parameters to build a given job. This allows you to start that job and specify the parameters you want to pass in. If you have a job which takes parameters that are pointed at a given JPG then you would pass those same parameters here.

**Comment by liuzhi-vip** [comment]
Thank you very much for your answer
