### ISSUE TITLE
JenkinsFallbacks#getErrors NPEs on message from ForbiddenException

### ISSUE THREAD

**Issue by isker** [cdancy/jenkins-rest#62]
When my bearer auth failed, a ForbiddenException was thrown with the message: 
```
<html><head><meta http-equiv='refresh' content='1;url=/login?from=%2Fjob%2Fmicroservices-build%2Fbuild'/><script>window.location.replace('/login?from=%2Fjob%2Fmicroservices-build%2Fbuild');</script></head><body style='background-color:white; color:white;'>


Authentication required
<!--
You are authenticated as: anonymous
Groups that you are in:
  
Permission you need to have (but didn't): hudson.model.Item.Build
 ... which is implied by: hudson.security.Permission.GenericUpdate
 ... which is implied by: hudson.security.Permission.GenericWrite
 ... which is implied by: hudson.model.Hudson.Administer
-->

</body></html>
```

JenkinsFallbacks attempts to parse this message at https://github.com/cdancy/jenkins-rest/blob/b171a7ceac9341fddd41af2121280c99d2c883ae/src/main/java/com/cdancy/jenkins/rest/fallbacks/JenkinsFallbacks.java#L155-L163
The `message` var ends up being null and is not marked as `@Nullable` on `Error`, so AutoValue throws an NPE.

### Expected Behavior
No NPE.

### Current Behavior
NPE.

### Context
This is happening when my auth is rejected on an API action that requires auth (building a Job).

### Steps to Reproduce (for bugs)
I don't have a reproducing project to share.  Let me know if one is needed.

### Your Environment
Jenkins 2.150.1 (November 2018)

**Comment by cdancy** [comment]
@isker this should be an easy fix. Care to send in a PR?

**Comment by martinda** [comment]
@isker What do you mean by "bearer auth"? Do you mean the Jenkins API Token?

**Comment by isker** [comment]
@martinda https://github.com/cdancy/jenkins-rest/blob/b171a7ceac9341fddd41af2121280c99d2c883ae/src/main/java/com/cdancy/jenkins/rest/JenkinsAuthentication.java#L78-L88

In related news, as I commented on https://github.com/cdancy/jenkins-rest/issues/50#issuecomment-499515092, there seems to be some conflicting overloading of the word `token` between this Java API and the `token` query parameter on the `build[WithParameters]` Jenkins REST APIs.  Before reading the code I had thought this `token` method was going to provide that query parameter.
