### ISSUE TITLE
Travis having issue with OracleJDK8

### ISSUE THREAD

**Issue by choweiyuan** [cdancy/jenkins-rest#65]
Build pretty much failing straightaway, see :
https://travis-ci.org/choweiyuan/jenkins-rest/builds/568944435

The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .

Workaround seems to be to use openjdk8
https://travis-ci.community/t/error-installing-oraclejdk8-expected-feature-release-number-in-range-of-9-to-14-but-got-8/3766/5

**Comment by cdancy** [comment]
Closing via #66 being merged
