### ISSUE TITLE
First QueueItem parameter is merged with second one

### ISSUE THREAD

**Issue by martinda** [cdancy/jenkins-rest#7]
### Expected Behavior

QueueItem parameters are correct.

### Current Behavior

The first QueueItem parameter is merged with the second one.

### Context

This causes confusing when looking at the queue item while debugging other issues.

### Steps to Reproduce (for bugs)

See https://gist.github.com/martinda/ab13617fe7bcb663a7d40c4ea73de5bf

### Your Environment

Linux, jenkins-rest 0.0.6.

I have prepared a PR which will show up shortly.

**Comment by cdancy** [comment]
Closing as functionality has been merged.
