### ISSUE TITLE
[Question] How to stop build job using rest ? 

### ISSUE THREAD

**Issue by ktjooho** [cdancy/jenkins-rest#73]
I haven't found any api to stop build job.

There is no related method to stop it in JobsApi interface.

I would like to know whether it is intended. 

Thank you.

**Comment by cdancy** [comment]
@ktjooho it would appear no. I could have sworn I/someone-from-the-community coded this up at some point but I guess not. Should be easy enough to do. We do have the [QueueAPI](https://github.com/cdancy/jenkins-rest/blob/master/src/main/java/com/cdancy/jenkins/rest/features/QueueApi.java) which you can use to stop a job that has NOT been queued yet.

In either event it should be easy enough to do after looking at the [DOCS](https://wiki.jenkins.io/display/JENKINS/Aborting+a+build). Care to give this a go or were you looking for one of our contributors to take this on?

**Comment by ktjooho** [comment]
I tried to use QueueAPI but failed in build stage.
I wanted to abort a job during build stage.
In the end, I resolved this issue using raw http to kill(not abort) the job request call using general http client library like RestTemplate.
