### ISSUE TITLE
Artifact.displayPath can be null

### ISSUE THREAD

**Issue by liptga** [cdancy/jenkins-rest#77]
### Expected Behavior
I expect if jenkins sends an artifact without displaypath, it works

### Current Behavior
I get a NullPointerException from the generated AutoValue class

### Context
I was connecting to a jenkins instance with 2.7xx version (i do not remember exactly), and when I tried to fetch information about builds, it failed.

### Steps to Reproduce (for bugs)
Without such a job it would be difficult I know.

### Your Environment
Jenkins 2.7xx

**Comment by cdancy** [comment]
Closed via #78
