### ISSUE TITLE
Can't find Nullable

### ISSUE THREAD

**Issue by choweiyuan** [cdancy/jenkins-rest#80]
### Current Behavior
Might be a developer thing, I can't run tests locally without javax.annotation.Nullable

### Steps to Reproduce (for bugs)
#77 's fix Artifact.java seems to be using
`import javax.annotation.Nullable;
`

![image](https://user-images.githubusercontent.com/4201614/72721716-9d541580-3b74-11ea-8362-642d26306f12.png)

which probably doesn't exist by default, have to include a separate jar for this. 
https://stackoverflow.com/questions/19030954/cant-find-nullable-inside-javax-annotation

Throughout the project, ` org.jclouds.javax.annotation.Nullable` is used instead.

### Your Environment
IntelliJ IDEA 2019.3.1

**Comment by martinda** [comment]
@choweiyuan Try building from the command line: `./gradlew build`. Also check your Java version.

**Comment by choweiyuan** [comment]
Okay that worked. But is that the right package to be used for `Nullable`
If you're fine with `javax.annotation.Nullable` rather than `org.jclouds.javax.annotation.Nullable` I'm happy to close this

**Comment by cdancy** [comment]
@choweiyuan to side-step these problems we _should_ use the jclouds version as newer releases of the JDK have this in a separate artifact. We could search through our code and remove/replace if someone is up for it. Any takers? :)
