### ISSUE TITLE
JobApi.jobInfo doesn't work with folder paths that have spaces

### ISSUE THREAD

**Issue by blajoie55** [cdancy/jenkins-rest#82]
When calling jobInfo on the JobApi and passing in a folder that has spaces in it, the method always returns null. It should return the JobInfo object

Here's some code demonstrating the issue I'm experiencing:

`JenkinsClient jenkinsClient = JenkinsClient.builder()
.endPoint("https://jenkins.vestmarkeng.com")
.credentials("${jenkinsUser}:${jenkinsPass}")
.build();

println jenkinsClient.api().jobsApi().jobInfo("products/vestmarkone/Standalone Integration Test", "release%2F8.2"); // always returns null, doesn't seem to like spaces in the folder path

println jenkinsClient.api().jobsApi().jobInfo("products/vestmarkone/Standalone%20Integration%20Test", "release%2F8.2"); // URL encoded space doesn't work either

println jenkinsClient.api().jobsApi().jobList("products/vestmarkone/Standalone Integration Test"); // this works even though there are spaces in the folder path`

**Comment by cdancy** [comment]
@blajoie55 interesting. There must be a bug somewhere. A different path parser is in use and so probably one works whereas the other is buggy. Care to take a look into things and/or send in a PR to fix things? Maybe consolidate to just using 1?

**Comment by blajoie55** [comment]
@cdancy whenever time permits on my end, I'll set up a dev env for jenkins-rest to step debug through the jenkins-rest src code in eclipse and find the cause and come up with a solutikon

**Comment by blajoie55** [comment]
Got some time to look more into this. No bug here. User error. I didn't realize my company only selected a handful of release branches (not all release branches) for the pipeline I was trying to fetch, i.e. the pipeline that had spaces in the item name
