### ISSUE TITLE
Use Dependabot to automate dependency fixes

### ISSUE THREAD

**Issue by choweiyuan** [cdancy/jenkins-rest#83]
### Current Behavior
Currently we have to update dependency manually if need be (for example CVE/OWASP security issue arises for one of the dependencies)

### Context
https://dependabot.com/#features probably good practice to automate and giving confidence to user that all the dependencies are up to date/secure.

**Comment by cdancy** [comment]
@choweiyuan is this easy enough to wire up? Haven't played around with this integration yet

**Comment by choweiyuan** [comment]
Don't know, have to test it out and get back to you on that!

**Comment by martinda** [comment]
Hi! If you want to learn more about dependabot, we had a recent Jenkins meetup where it was presented, it's a bit jenkins specific but I thought it was useful for me to learn about it. They also talk about the gotchas. The [recording](https://www.youtube.com/watch?v=RXIJpjYlECQ) and [slides](https://drive.google.com/file/d/1YbuiqyP1McNuo-Vc3wjpIBOXE3RUTZ-R/view) have been published.

**Comment by choweiyuan** [comment]
Tried it fairly quickly, took less than 2 minutes to allow Dependabot to have access to your repos 

1. go to dependabot.com 
2. login with your Github account, then choose your repos of your interests.
3. Settings involved
![Dependabot](https://user-images.githubusercontent.com/4201614/77779198-0ad76300-704a-11ea-8c10-16b70a6c1d7e.PNG)

Example PRs generated: https://github.com/choweiyuan/bcexample/pulls

**Comment by cdancy** [comment]
@choweiyuan just enabled .... lets see what happens...

**Comment by cdancy** [comment]
@choweiyuan I've applied dependabot to this project as well as my `artifactory-rest` and `bitbucket-rest` projects. Thanks for this as it's very useful!
