### ISSUE TITLE
Ability to Restart from Stage

### ISSUE THREAD

**Issue by choweiyuan** [cdancy/jenkins-rest#87]
### Expected Behavior
https://jenkins.io/doc/book/pipeline/running-pipelines/#restart-from-a-stage
I'd like to programmatic be able to restart from stage

GET: https://url/job/{folderName}/job/{jobName}/{jobNumber}/restart/api/json?pretty=true 
will list restartable stage

```
{
  "_class" : "org.jenkinsci.plugins.pipeline.modeldefinition.actions.RestartDeclarativePipelineAction",
  "restartEnabled" : true,
  "restartableStages" : [
    "Notify Stash..",
    "Stage A",
    "Stage B",
    "Stage C",
    "Stage D"
  ]
}
```

POST: https://url/job/{folderName}/job/{jobName}/{jobNumber}/restart/restart
API to restart from stage
```
stageName: {stageName}
Jenkins-Crumb: {jenkinsCrumb}
json: {"stageName": {stageName}, "Jenkins-Crumb": {jenkinsCrumb}}
Submit: Run
```

### Current Behavior
Jenkins-rest doesn't support this at the moment

### Context
Should a job fail, rather than going to the jenkins to re-run it, I'd like to programmatically re-run from a stage.

**Comment by cdancy** [comment]
@choweiyuan don't have time at the moment but feel free to send in a PR and I can review and merge rather quickly. Shouldn't be bad to knock out.

**Comment by cdancy** [comment]
Closing as issue has gone stale. Feel free to re-open if you want to discuss further.

**Comment by Om4AI** [comment]
@choweiyuan @cdancy was this issue resolved, can you suggest any solution, if it was resolved.

**Comment by choweiyuan** [comment]
> @choweiyuan @cdancy was this issue resolved, can you suggest any solution, if it was resolved.

**Comment by Om4AI** [comment]
@choweiyuan then how can we trigger the restart from stage or restart the previously failed build using Jenkins API ? Any workaround for this?

**Comment by choweiyuan** [comment]
@Om4AI

AFAIK you can't do it with this library atm. 

If you read the first post, the suggestion is that you could use the following POST request to restart from stage:

POST: [https://url/job/{folderName}/job/{jobName}/{jobNumber}/restart/restart]
